name: Reusable Dependency Review

on:
  workflow_call:

jobs:
  dependency-review:
    name: Review Dependency Changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Run GitHub Dependency Review
        uses: actions/dependency-review-action@v5
        with:
          fail-on-severity: high
